Fix a bug where a queryIndex with a pair at exactly the same position would yield a query-index-occurrences=1 on the first encounter of the queryIndex. Now it correctly return 2 on the first encounter. This would cause the following exception when coding with hybrid-1:
java.lang.IllegalArgumentException: The argument -1 is negative
     at it.unimi.dsi.io.OutputBitStream.writeNibble(OutputBitStream.java:1209)
     at edu.cornell.med.icb.goby.alignments.AlignmentCollectionHandler.writeQueryIndices(AlignmentCollectionHandler.java:229)
     at edu.cornell.med.icb.goby.alignments.AlignmentCollectionHandler.writeCompressed(AlignmentCollectionHandler.java:536)
     at edu.cornell.med.icb.goby.alignments.AlignmentCollectionHandler.compressCollection(AlignmentCollectionHandler.java:120)
     at edu.cornell.med.icb.goby.compression.HybridChunkCodec1.encode(HybridChunkCodec1.java:65)
     at edu.cornell.med.icb.goby.compression.MessageChunksWriter.flush(MessageChunksWriter.java:172)
     at edu.cornell.med.icb.goby.compression.MessageChunksWriter.close(MessageChunksWriter.java:205)
     at edu.cornell.med.icb.goby.alignments.AlignmentWriter.close(AlignmentWriter.java:402)
     at edu.cornell.med.icb.goby.modes.AbstractAlignmentToCompactMode.execute(AbstractAlignmentToCompactMode.java:242)
     at edu.cornell.med.icb.goby.modes.GenericToolsDriver.execute(GenericToolsDriver.java:212)
     at edu.cornell.med.icb.goby.modes.GobyDriver.main(GobyDriver.java:54)


git-svn-id: https://pbtech-vc.med.cornell.edu/public/svn/icb/trunk/goby@31208 60cd2ccc-2b05-0410-9566-da273a940bff